## 📑 Refrences

* [**Towards Data Science**](https://towardsdatascience.com/evaluation-metrics-for-recommendation-systems-an-overview-71290690ecba/)
* [**Medium**](https://medium.com/data-science/metrics-of-recommender-systems-cde64042127a)
* [**Evidently AI**](https://www.evidentlyai.com/ranking-metrics/evaluating-recommender-systems)

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
from Column import column
import re

## 🟢 Loading Dataset

In [2]:
users = pd.read_csv("Datasets/Users.csv")
users.head()

,user_id,username,place_id,place_name,rating
0,04fab766-306b-4f35-a83e-4655f052392d,dina_ali,7,Obelisk of Senusret I,3
1,04fab766-306b-4f35-a83e-4655f052392d,dina_ali,71,Graeco-Roman Museum,2
2,04fab766-306b-4f35-a83e-4655f052392d,dina_ali,63,Alexandria Museum of Fine Arts,3
3,04fab766-306b-4f35-a83e-4655f052392d,dina_ali,58,Agricultural Museum,1
4,04fab766-306b-4f35-a83e-4655f052392d,dina_ali,36,Ras Mohammed National Park,5

In [3]:
rows , columns = users.shape
print(f"Users Dataset have {rows} row and {columns} Column")

Users Dataset have 1038 row and 5 Column

In [4]:
places = pd.read_csv("Datasets/Places.csv")
places.head()

,ID,Name,Description,Location,Latitude,Longitude,Type Of Site,Historical Era,Key Features,Opening Hours,Typical Visit Duration,Entry Fee,ImageLink
0,1,Pyramids of Giza,"Comprising the Great Pyramid of Khufu, the Pyr...",Giza,29.977494,31.132504,Ancient Sites,Pharaonic,"['Pharaonic tombs', 'UNESCO World Heritage Sit...",07:00 AM - 04:00 PM,2 - 3 hours,Foreigners Adult: 700 EGP\nForeigners Student:...,https://wsestolbnlfafbbhelee.supabase.co/stora...
1,2,Dahshur Pyramids,This archaeological area features the Bent Pyr...,Giza,29.822100,31.205500,Ancient Sites,Pharaonic,"['Bent Pyramid', 'Red Pyramid', 'Transition in...",08:00 AM - 05:00 PM,1 - 2 hours,Foreigners Adult: 200 EGP\nForeigners Student:...,https://wsestolbnlfafbbhelee.supabase.co/stora...
2,3,Colossi of Memnon,The Colossi of Memnon are two massive stone st...,luxor,25.725000,32.605000,Ancient Sites,"18th Dynasty\n(~Amenhotep III, c. 1390-1353 BCE)","['Two seated colossi, 18 m tall', 'Quartzite s...",06:00 AM - 05:00 PM,30 - 60 minutes,Free,https://wsestolbnlfafbbhelee.supabase.co/stora...
3,4,Memphis,"Once the capital of Lower Egypt, Memphis was a...",Giza,29.844600,31.250400,Ancient Sites,Pharaonic,"['Colossal Ramses II statue', 'Former capital ...",08:00 AM - 05:00 PM,1 - 2 hours,Foreigners Adult: 160 EGP\nForeigners Student:...,https://wsestolbnlfafbbhelee.supabase.co/stora...
4,5,Elephantine Island,Historically marking Egypt's southern boundary...,Aswan,24.084312,32.883934,Ancient Sites,Various,"['Temple of Khnum ruins', 'Nubian culture', 'N...",09:00 AM - 04:00 PM,1 - 2 hours,Foreigners Adult: 200 EGP\nForeigners Student:...,https://wsestolbnlfafbbhelee.supabase.co/stora...

In [5]:
rows , columns = places.shape
print(f"Places Dataset have {rows} row and {columns} Column")

Places Dataset have 162 row and 13 Column

## 🚩 Feature Engineering 
* Make Additional Feature included Places Features

In [6]:
places["PlaceDescription"] = places["Description"] + " " + places["Location"] + " " + \
" " + places["Historical Era"] + " "+ places["Type Of Site"] + " " + places["Key Features"]

## 🚩 Choosing Features that will matter to Text Preprocessing

In [7]:
df = places.loc[ : , ["ID","Name","PlaceDescription"]]

## 📍 Lowering Text

In [8]:
df["Cleaned_Description"] = df["PlaceDescription"].apply(lambda x:x.lower())
df

,ID,Name,PlaceDescription,Cleaned_Description
0,1,Pyramids of Giza,"Comprising the Great Pyramid of Khufu, the Pyr...","comprising the great pyramid of khufu, the pyr..."
1,2,Dahshur Pyramids,This archaeological area features the Bent Pyr...,this archaeological area features the bent pyr...
2,3,Colossi of Memnon,The Colossi of Memnon are two massive stone st...,the colossi of memnon are two massive stone st...
3,4,Memphis,"Once the capital of Lower Egypt, Memphis was a...","once the capital of lower egypt, memphis was a..."
4,5,Elephantine Island,Historically marking Egypt's southern boundary...,historically marking egypt's southern boundary...
...,...,...,...,...
157,158,Mortuary Temple of Hatshepsut,The Mortuary Temple of Queen Hatshepsut is an ...,the mortuary temple of queen hatshepsut is an ...
158,159,Temple of Ramses III,Medinet Habu is the mortuary temple of Ramses ...,medinet habu is the mortuary temple of ramses ...
159,160,Ramesseum (Mortuary Temple of Ramses II),The Ramesseum is the mortuary temple of Pharao...,the ramesseum is the mortuary temple of pharao...
160,161,Temple of Seti I,"The Temple of Seti I, also known as the Great ...","the temple of seti i, also known as the great ..."
161,162,Mortuary Temple of Merneptah,The Mortuary Temple of Merneptah (also spelled...,the mortuary temple of merneptah (also spelled...

In [9]:
desc = column(Column_name="Cleaned_Description",Dataset=df)

## 📍 Start Calling **`nltk`** Modules

In [10]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

## 📍 Tokenizing Places Description

In [11]:
desc.Update(func=lambda x: word_tokenize(x))

,ID,Name,PlaceDescription,Cleaned_Description
0,1,Pyramids of Giza,"Comprising the Great Pyramid of Khufu, the Pyr...","[comprising, the, great, pyramid, of, khufu, ,..."
1,2,Dahshur Pyramids,This archaeological area features the Bent Pyr...,"[this, archaeological, area, features, the, be..."
2,3,Colossi of Memnon,The Colossi of Memnon are two massive stone st...,"[the, colossi, of, memnon, are, two, massive, ..."
3,4,Memphis,"Once the capital of Lower Egypt, Memphis was a...","[once, the, capital, of, lower, egypt, ,, memp..."
4,5,Elephantine Island,Historically marking Egypt's southern boundary...,"[historically, marking, egypt, 's, southern, b..."
...,...,...,...,...
157,158,Mortuary Temple of Hatshepsut,The Mortuary Temple of Queen Hatshepsut is an ...,"[the, mortuary, temple, of, queen, hatshepsut,..."
158,159,Temple of Ramses III,Medinet Habu is the mortuary temple of Ramses ...,"[medinet, habu, is, the, mortuary, temple, of,..."
159,160,Ramesseum (Mortuary Temple of Ramses II),The Ramesseum is the mortuary temple of Pharao...,"[the, ramesseum, is, the, mortuary, temple, of..."
160,161,Temple of Seti I,"The Temple of Seti I, also known as the Great ...","[the, temple, of, seti, i, ,, also, known, as,..."
161,162,Mortuary Temple of Merneptah,The Mortuary Temple of Merneptah (also spelled...,"[the, mortuary, temple, of, merneptah, (, also..."

## 📍 Removing StopWords

In [12]:
stopwords_ = stopwords.words("english") 
print(f"Number of Stopwords in English = {len(stopwords_)} word")

Number of Stopwords in English = 198 word

In [13]:
def Remove_Stopwords(Text:str)-> list:
    return [word for word in Text if word not in stopwords_]

In [14]:
desc.Update(lambda x:Remove_Stopwords(Text=x))

,ID,Name,PlaceDescription,Cleaned_Description
0,1,Pyramids of Giza,"Comprising the Great Pyramid of Khufu, the Pyr...","[comprising, great, pyramid, khufu, ,, pyramid..."
1,2,Dahshur Pyramids,This archaeological area features the Bent Pyr...,"[archaeological, area, features, bent, pyramid..."
2,3,Colossi of Memnon,The Colossi of Memnon are two massive stone st...,"[colossi, memnon, two, massive, stone, statues..."
3,4,Memphis,"Once the capital of Lower Egypt, Memphis was a...","[capital, lower, egypt, ,, memphis, major, rel..."
4,5,Elephantine Island,Historically marking Egypt's southern boundary...,"[historically, marking, egypt, 's, southern, b..."
...,...,...,...,...
157,158,Mortuary Temple of Hatshepsut,The Mortuary Temple of Queen Hatshepsut is an ...,"[mortuary, temple, queen, hatshepsut, ancient,..."
158,159,Temple of Ramses III,Medinet Habu is the mortuary temple of Ramses ...,"[medinet, habu, mortuary, temple, ramses, iii,..."
159,160,Ramesseum (Mortuary Temple of Ramses II),The Ramesseum is the mortuary temple of Pharao...,"[ramesseum, mortuary, temple, pharaoh, ramses,..."
160,161,Temple of Seti I,"The Temple of Seti I, also known as the Great ...","[temple, seti, ,, also, known, great, temple, ..."
161,162,Mortuary Temple of Merneptah,The Mortuary Temple of Merneptah (also spelled...,"[mortuary, temple, merneptah, (, also, spelled..."

## 📍 Lemmatizing Words

In [15]:
lemma = WordNetLemmatizer()
def lemmatize_word(Text:str) -> list:
    return [lemma.lemmatize(word=word,pos="v") for word in Text]

In [16]:
desc.Update(func=lambda x:lemmatize_word(Text=x))

,ID,Name,PlaceDescription,Cleaned_Description
0,1,Pyramids of Giza,"Comprising the Great Pyramid of Khufu, the Pyr...","[comprise, great, pyramid, khufu, ,, pyramid, ..."
1,2,Dahshur Pyramids,This archaeological area features the Bent Pyr...,"[archaeological, area, feature, bend, pyramid,..."
2,3,Colossi of Memnon,The Colossi of Memnon are two massive stone st...,"[colossi, memnon, two, massive, stone, statues..."
3,4,Memphis,"Once the capital of Lower Egypt, Memphis was a...","[capital, lower, egypt, ,, memphis, major, rel..."
4,5,Elephantine Island,Historically marking Egypt's southern boundary...,"[historically, mark, egypt, 's, southern, boun..."
...,...,...,...,...
157,158,Mortuary Temple of Hatshepsut,The Mortuary Temple of Queen Hatshepsut is an ...,"[mortuary, temple, queen, hatshepsut, ancient,..."
158,159,Temple of Ramses III,Medinet Habu is the mortuary temple of Ramses ...,"[medinet, habu, mortuary, temple, ramses, iii,..."
159,160,Ramesseum (Mortuary Temple of Ramses II),The Ramesseum is the mortuary temple of Pharao...,"[ramesseum, mortuary, temple, pharaoh, ramses,..."
160,161,Temple of Seti I,"The Temple of Seti I, also known as the Great ...","[temple, seti, ,, also, know, great, temple, a..."
161,162,Mortuary Temple of Merneptah,The Mortuary Temple of Merneptah (also spelled...,"[mortuary, temple, merneptah, (, also, spell, ..."

## 📍 Trans List to String

In [17]:
desc.Update(func=lambda x:" ".join(x))

,ID,Name,PlaceDescription,Cleaned_Description
0,1,Pyramids of Giza,"Comprising the Great Pyramid of Khufu, the Pyr...","comprise great pyramid khufu , pyramid khafre ..."
1,2,Dahshur Pyramids,This archaeological area features the Bent Pyr...,archaeological area feature bend pyramid red p...
2,3,Colossi of Memnon,The Colossi of Memnon are two massive stone st...,colossi memnon two massive stone statues phara...
3,4,Memphis,"Once the capital of Lower Egypt, Memphis was a...","capital lower egypt , memphis major religious ..."
4,5,Elephantine Island,Historically marking Egypt's southern boundary...,"historically mark egypt 's southern boundary ,..."
...,...,...,...,...
157,158,Mortuary Temple of Hatshepsut,The Mortuary Temple of Queen Hatshepsut is an ...,mortuary temple queen hatshepsut ancient funer...
158,159,Temple of Ramses III,Medinet Habu is the mortuary temple of Ramses ...,"medinet habu mortuary temple ramses iii , buil..."
159,160,Ramesseum (Mortuary Temple of Ramses II),The Ramesseum is the mortuary temple of Pharao...,"ramesseum mortuary temple pharaoh ramses ii , ..."
160,161,Temple of Seti I,"The Temple of Seti I, also known as the Great ...","temple seti , also know great temple abydos , ..."
161,162,Mortuary Temple of Merneptah,The Mortuary Temple of Merneptah (also spelled...,mortuary temple merneptah ( also spell merenpt...

## 📍 Remove any Punctuation

In [18]:
desc.Update(func=lambda x:re.sub(pattern=r'[\[\]]|[^a-zA-Z\s]',repl=" ",string=x))

,ID,Name,PlaceDescription,Cleaned_Description
0,1,Pyramids of Giza,"Comprising the Great Pyramid of Khufu, the Pyr...",comprise great pyramid khufu pyramid khafre ...
1,2,Dahshur Pyramids,This archaeological area features the Bent Pyr...,archaeological area feature bend pyramid red p...
2,3,Colossi of Memnon,The Colossi of Memnon are two massive stone st...,colossi memnon two massive stone statues phara...
3,4,Memphis,"Once the capital of Lower Egypt, Memphis was a...",capital lower egypt memphis major religious ...
4,5,Elephantine Island,Historically marking Egypt's southern boundary...,historically mark egypt s southern boundary ...
...,...,...,...,...
157,158,Mortuary Temple of Hatshepsut,The Mortuary Temple of Queen Hatshepsut is an ...,mortuary temple queen hatshepsut ancient funer...
158,159,Temple of Ramses III,Medinet Habu is the mortuary temple of Ramses ...,medinet habu mortuary temple ramses iii buil...
159,160,Ramesseum (Mortuary Temple of Ramses II),The Ramesseum is the mortuary temple of Pharao...,ramesseum mortuary temple pharaoh ramses ii ...
160,161,Temple of Seti I,"The Temple of Seti I, also known as the Great ...",temple seti also know great temple abydos ...
161,162,Mortuary Temple of Merneptah,The Mortuary Temple of Merneptah (also spelled...,mortuary temple merneptah also spell merenpt...

## 📍 Remove any Single Letter

In [19]:
desc.Update(lambda x:re.sub(pattern=r"\s[a-zA-z]{1}\s",repl=" ",string=x))

,ID,Name,PlaceDescription,Cleaned_Description
0,1,Pyramids of Giza,"Comprising the Great Pyramid of Khufu, the Pyr...",comprise great pyramid khufu pyramid khafre ...
1,2,Dahshur Pyramids,This archaeological area features the Bent Pyr...,archaeological area feature bend pyramid red p...
2,3,Colossi of Memnon,The Colossi of Memnon are two massive stone st...,colossi memnon two massive stone statues phara...
3,4,Memphis,"Once the capital of Lower Egypt, Memphis was a...",capital lower egypt memphis major religious ...
4,5,Elephantine Island,Historically marking Egypt's southern boundary...,historically mark egypt southern boundary i...
...,...,...,...,...
157,158,Mortuary Temple of Hatshepsut,The Mortuary Temple of Queen Hatshepsut is an ...,mortuary temple queen hatshepsut ancient funer...
158,159,Temple of Ramses III,Medinet Habu is the mortuary temple of Ramses ...,medinet habu mortuary temple ramses iii buil...
159,160,Ramesseum (Mortuary Temple of Ramses II),The Ramesseum is the mortuary temple of Pharao...,ramesseum mortuary temple pharaoh ramses ii ...
160,161,Temple of Seti I,"The Temple of Seti I, also known as the Great ...",temple seti also know great temple abydos ...
161,162,Mortuary Temple of Merneptah,The Mortuary Temple of Merneptah (also spelled...,mortuary temple merneptah also spell merenpt...

## 📍 Remove Extra Spaces

In [20]:
desc.Update(lambda x:re.sub(pattern=r"\s+",repl=" ",string=x))

,ID,Name,PlaceDescription,Cleaned_Description
0,1,Pyramids of Giza,"Comprising the Great Pyramid of Khufu, the Pyr...",comprise great pyramid khufu pyramid khafre py...
1,2,Dahshur Pyramids,This archaeological area features the Bent Pyr...,archaeological area feature bend pyramid red p...
2,3,Colossi of Memnon,The Colossi of Memnon are two massive stone st...,colossi memnon two massive stone statues phara...
3,4,Memphis,"Once the capital of Lower Egypt, Memphis was a...",capital lower egypt memphis major religious po...
4,5,Elephantine Island,Historically marking Egypt's southern boundary...,historically mark egypt southern boundary isla...
...,...,...,...,...
157,158,Mortuary Temple of Hatshepsut,The Mortuary Temple of Queen Hatshepsut is an ...,mortuary temple queen hatshepsut ancient funer...
158,159,Temple of Ramses III,Medinet Habu is the mortuary temple of Ramses ...,medinet habu mortuary temple ramses iii build ...
159,160,Ramesseum (Mortuary Temple of Ramses II),The Ramesseum is the mortuary temple of Pharao...,ramesseum mortuary temple pharaoh ramses ii bu...
160,161,Temple of Seti I,"The Temple of Seti I, also known as the Great ...",temple seti also know great temple abydos sign...
161,162,Mortuary Temple of Merneptah,The Mortuary Temple of Merneptah (also spelled...,mortuary temple merneptah also spell merenptah...

## ✔ Start Building Model

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors

## ✔ Vectorize Places Description

In [22]:
tfidf = TfidfVectorizer(stop_words="english")

tfidf_vctors = tfidf.fit_transform(df["Cleaned_Description"])

In [23]:
print(f"Number of Words based in tfidf = {len(tfidf.get_feature_names_out())} Word")

Number of Words based in tfidf = 1932 Word

## ✔ Get Similaraties between places by KNN

In [24]:
knn = NearestNeighbors(metric="cosine",algorithm="brute",n_neighbors=10)
knn.fit(tfidf_vctors)

NearestNeighbors(algorithm='brute', metric='cosine', n_neighbors=10)

## 🟢 Build Recommendation System

In [25]:
def get_similar_places(target_id: int, k: int = 6):
    row_idx = target_id - 1     
    distance, indices = knn.kneighbors(tfidf_vctors[row_idx], n_neighbors=k)  

    
    distance = distance.flatten()
    indices = indices.flatten()

    for dist, idx in zip(distance, indices):
        if idx == row_idx:
            continue
            
        row = df.iloc[idx, :].copy()
        row["distance"] = dist
        yield row

pd.DataFrame(get_similar_places(target_id=1,k=10)).sort_values(by="distance")

,ID,Name,PlaceDescription,Cleaned_Description,distance
1,2,Dahshur Pyramids,This archaeological area features the Bent Pyr...,archaeological area feature bend pyramid red p...,0.455204
5,6,Abusir Necropolis,Abusir is an ancient Egyptian necropolis locat...,abusir ancient egyptian necropolis locate giza...,0.544030
34,35,Saqqara Necropolis,"Part of the ancient burial grounds of Memphis,...",part ancient burial ground memphis saqqara bes...,0.639727
33,34,Great Sphinx of Giza,"Carved from a single piece of limestone, the S...",carve single piece limestone sphinx think repr...,0.765426
15,16,Valley of the Kings,The Valley of the Kings is an ancient burial g...,valley kings ancient burial grind egypt years ...,0.808926
12,13,Maqaber Al-Mualla,Maqaber Al-Mualla is an ancient burial site in...,maqaber al mualla ancient burial site luxor an...,0.862888
49,50,Grand Egyptian Museum,One of the world largest repositories of ancie...,one world largest repositories ancient egyptia...,0.880036
85,86,Saint Catherine's Monastery,"Saint Catherine's Monastery, located at the fo...",saint catherine monastery locate foot mount si...,0.889877
58,59,Pharaonic Village,The Pharaonic Village is a living museum near ...,pharaonic village live museum near giza found ...,0.890482

## ✅ Build System with FAISS Lib & Sentence Transformer

In [60]:
import faiss
from sentence_transformers import SentenceTransformer

In [ ]:
model = SentenceTransformer(model_name_or_path="all-MiniLM-L6-v2")
descriptions = model.encode(df["PlaceDescription"]).astype(np.float32)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [67]:
descriptions.shape

(162, 384)

In [ ]:
tfidf_array = tfidf_vctors.toarray().astype(np.float32)
faiss.normalize_L2(descriptions)


dim = descriptions.shape[1]
index = faiss.IndexFlatIP(dim)
index.add(descriptions)

In [82]:
np.save("Places_Embeddings.npy", descriptions)
faiss.write_index(index, "faiss_Places_Embeddings.index")

In [ ]:
tfidf_array = np.load("Places_Embeddings.npy")
index = faiss.read_index("faiss_Places_Embeddings.index")


def get_similar_places(target_id: int, k: int = 6):
    row_idx = target_id - 1     
    query_vector = tfidf_array[row_idx : row_idx+1] 

    distance, indices = index.search(query_vector, k)

    distance = distance.flatten()
    indices = indices.flatten()

    for dist, idx in zip(distance, indices):
        if idx == row_idx:
            continue
            
        row = df.iloc[idx, :].copy()
        row["distance"] = dist
        yield row
        
pd.DataFrame(get_similar_places(target_id=1, k=10)).sort_values(by="distance", ascending=False)

(1, 384)

,ID,Name,PlaceDescription,Cleaned_Description,distance
33,34,Great Sphinx of Giza,"Carved from a single piece of limestone, the S...",carve single piece limestone sphinx think repr...,0.677589
1,2,Dahshur Pyramids,This archaeological area features the Bent Pyr...,archaeological area feature bend pyramid red p...,0.661301
34,35,Saqqara Necropolis,"Part of the ancient burial grounds of Memphis,...",part ancient burial ground memphis saqqara bes...,0.647210
58,59,Pharaonic Village,The Pharaonic Village is a living museum near ...,pharaonic village live museum near giza found ...,0.589649
5,6,Abusir Necropolis,Abusir is an ancient Egyptian necropolis locat...,abusir ancient egyptian necropolis locate giza...,0.586642
49,50,Grand Egyptian Museum,One of the world largest repositories of ancie...,one world largest repositories ancient egyptia...,0.580442
77,78,City of the Dead,A vast Islamic necropolis in Cairo dating back...,vast islamic necropolis cairo date back th cen...,0.570963
15,16,Valley of the Kings,The Valley of the Kings is an ancient burial g...,valley kings ancient burial grind egypt years ...,0.569874
53,54,National Museum of Egyptian Civilization,A modern museum that narrates Egypt's history ...,modern museum narrate egypt history prehistori...,0.547439

In [94]:
tfidf_array.shape

(162, 384)

---

<h1 align="center">The End of model 😎</h1>


---